 name: Cypress Tests

 on: [push]

 jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.7.0
      # Install NPM dependencies, cache them correctly
      # and run all Cypress tests
      - name: Cypress.io
        uses: cypress-io/github-action@v5.5.1 # use the explicit version number
        with:
            command: npm run cypress:runChrome
      - name: Slack Notification
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_USERNAME: panganibanmish.work
          SLACK_TITLE: test team
          SLACK_MESSAGE: "New Update: "
          SLACK_COLOR: ${{ job.status }}
